### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by LaptopRecai** [bwmsdroid/exitlag-hwid-bypass#1]
Maybe its fixed. But its not working for now. Did you test for latest version exitlag?

**Comment by bwmsdroid** [comment]
Hey!
I fixed it today, the problem was the address of rand function.
Now I am using GetProcAddress(GetModuleHandleA("ucrtbase"),"rand") to get the address of the rand function.

Could you try now?

**Comment by LaptopRecai** [comment]
Yes, its worked. Thaks bro
