### ISSUE TITLE
Não está funcionando

### ISSUE THREAD

**Issue by FelipeFMA** [bwmsdroid/exitlag-hwid-bypass#2]
Oi, eu to escrevendo em portugues porque vi q vc é br no seu perfil kk, eu n entendo muito de programação nem do github mas mas eu preciso baixar esse programa, como eu faço? meu ping ta ficano muito ruim eu usei exit lag e funcionou mas meus dias acabaram

**Comment by FelipeFMA** [comment]
Imagino que aqui seja para mandar erros, mas é que eu realmente n sei como entrar em contato 🙈

**Comment by FelipeFMA** [comment]
Consegui baixar, funcionou, muito bom

**Comment by bwmsdroid** [comment]
Legal! Se puder deixar uma estrela e fazer um fork eu agradeço :D
![image](https://user-images.githubusercontent.com/53904508/112162977-5542df80-8bcb-11eb-9159-6bf9aa691b80.png)
Tenha um ótimo dia!

**Comment by FelipeFMA** [comment]
Opa mano, funcionou uma vez mas agora parou de funcionar :(
Eu fiz logout, criei uma conta nova e apareceu q eu não tenho dias
![Capturar](https://user-images.githubusercontent.com/30672253/112630305-a1239d80-8df2-11eb-9d3e-b97057335f26.PNG)

**Comment by bwmsdroid** [comment]
Estranho, testei ontem e funcionou tranquilo. Já usei centenas de vezes este meu programa e nunca aconteceu este problema. Mesmo que a exitlag ou windows atualizasse, é pra continuar funcionando;
Qual a mensagem do programa?

**Comment by FelipeFMA** [comment]
> Estranho, testei ontem e funcionou tranquilo. Já usei centenas de vezes este meu programa e nunca aconteceu este problema. Mesmo que a exitlag ou windows atualizasse, é pra continuar funcionando;
> Qual a mensagem do programa?

The hook address was found. It is: 0x009CD497
The memory has been allocated. The address is: 0x04740000
Success. You can close this program and loggin to your new exitlag account!
Pressione qualquer tecla para continuar. . .

**Comment by FelipeFMA** [comment]
Eu preciso mt desse programa pq aqui em casa a internet fica muuuuito ruim a noite e o exitlag funciona, nunca que meus pais iriam deixar eu gastar dinheiro nele ;-;

**Comment by FelipeFMA** [comment]
por acaso tem que desinstalar e instalar de volta pra funcionar? eu n fiz isso

**Comment by bwmsdroid** [comment]
Faz isso, mas eu ainda não to entendendo porque n funciona...

**Comment by FelipeFMA** [comment]
Eu gravei pra te mostrar que não esta funcionando, fiz algo errado?
https://youtu.be/wjtt1r4T8v8

**Comment by bwmsdroid** [comment]
Tu fez certo. Seguinte, vamos ver o que tá dando erro.
Baixa o cheat engine e instala normal. Abre ele. Abre a exitlag. Abre o bypass.
Quando der mensagem de sucesso tu copia o endereço de memória que foi alocada, neste caso é 0x036F0000, mas muda toda a vez que abre o programa.
![image](https://user-images.githubusercontent.com/53904508/112635918-28850700-8e1b-11eb-8686-70b8b754f624.png)
Daí tu vai no cheat engine e seleciona o processo do bypass.
https://tecnoblog.net/334189/como-usar-cheat-engine-guia-completo/
Daí tu vai no memory view e aperta ctrol g. Vai aparecer uma mensagem e tu cola o endereço que tu copiou.
Me manda um printscreen da tela daí

**Comment by FelipeFMA** [comment]
Se eu entendi certo vc quer isso aqui 
![image](https://user-images.githubusercontent.com/30672253/112637253-2dd25980-8dfb-11eb-8e56-6d88dc7509ff.png)

**Comment by FelipeFMA** [comment]
![image](https://user-images.githubusercontent.com/30672253/112638239-45f6a880-8dfc-11eb-837b-81d2e3e5b712.png)

**Comment by bwmsdroid** [comment]
isso aí. tu fez certinho.
eu quero ver a parte de cima. A janela de baixo (o verde) não interessa.
Expande a janela de cima o máximo e me manda print de novo, please

**Comment by FelipeFMA** [comment]
![image](https://user-images.githubusercontent.com/30672253/112641441-a3402900-8dff-11eb-9e88-0acef8756e04.png)

**Comment by bwmsdroid** [comment]
fez certo!
![image](https://user-images.githubusercontent.com/53904508/112642016-a51ae400-8e21-11eb-8310-1ed27d6e2461.png)
vai neste endereço, clicka em cima (vai ficar azul) e aperta F5. Vai aparecer uma mensagem, aperta OK.
o endereço deve ficar em vermelho (significa que foi posto um breakpoint).
Daí tu faz login na exitlag. O breakpoint irá pausar o programa bem na hora de fazer o login e ficará em verde. Me manda um printscreen daí

**Comment by FelipeFMA** [comment]
![exitlag](https://user-images.githubusercontent.com/30672253/112643386-8f95c200-8e01-11eb-8988-512619a9f619.PNG)
![Captura de Tela (12)](https://user-images.githubusercontent.com/30672253/112643402-93294900-8e01-11eb-83a3-fa0fbd5cfa3e.png)

**Comment by bwmsdroid** [comment]
desculpa. é no endereço de baixo o JE. Aperta F5 em cima com JE para tirar o breakpoint, depois coloca no de baixo. Depois clicka em run

**Comment by FelipeFMA** [comment]
Não achei nenhum botão run, cliquei no f5, ta certo?
![image](https://user-images.githubusercontent.com/30672253/112645047-51999d80-8e03-11eb-9fb5-e34d958b2cda.png)
![image](https://user-images.githubusercontent.com/30672253/112645070-58c0ab80-8e03-11eb-85b8-c10d980fa0c4.png)

**Comment by FelipeFMA** [comment]
![image](https://user-images.githubusercontent.com/30672253/112648732-071a2000-8e07-11eb-9c1e-a2bb02c67e74.png)
demorou mas entendi kk

**Comment by bwmsdroid** [comment]
ok. isso mesmo
ali no canto superior direito, onde está EAX em azul. Clicka com o botão direito e vai aparecer follow em alguma coisa (n lembro); tu clicka nisso; daí tu expande (total) aquela janela que tu diminuiu a outra vez e me manda print

**Comment by FelipeFMA** [comment]
![image](https://user-images.githubusercontent.com/30672253/112652331-8ceb9a80-8e0a-11eb-9906-d9bd7ca37d7e.png)

**Comment by bwmsdroid** [comment]
faz assim. expande total o verdinho, põe todo pra direita.
daí tu click em algum dos veridinhos de dá ctrol + g. daí tu põe 0xFED180
me manda print

**Comment by FelipeFMA** [comment]
![image](https://user-images.githubusercontent.com/30672253/112654673-ddfc8e00-8e0c-11eb-9b65-2f121665a405.png)

**Comment by bwmsdroid** [comment]
Baixa esse ct aqui e vê se resolve: https://cdn.discordapp.com/attachments/806243189194227753/806248472189730867/exit_lag_bypass_cheat_engine.CT
É só colocar o processo da exitlag, ativar a caixinha e logar com a nova conta;
Depois pode fechar o cheat engine

**Comment by FelipeFMA** [comment]
Uhuuuu! funcionou !! Muito muito muito obrigado mesmo cara
![image](https://user-images.githubusercontent.com/30672253/112666454-700a9380-8e19-11eb-8123-7b751c4a68c0.png)

**Comment by FelipeFMA** [comment]
Então sempre que eu for criar uma conta nova eu vou ter que usar essa parada do cheat engine?

**Comment by bwmsdroid** [comment]
Boa!
Só vai ter que usar isso enquanto eu n resolvo essa merda.
Tenho que enteder qual é o problema. Talvez daqui uns dias eu peça sua ajuda para detectar o erro.
Em todo o caso, me manda um solicitação no discord: GatoLouco#3684

**Comment by FelipeFMA** [comment]
blz, te mandei uma solicitação, sou o Pipoco#8321
