### ISSUE TITLE
not working tried 2 new google accounts

### ISSUE THREAD

**Issue by belalninja** [bwmsdroid/exitlag-hwid-bypass#3]
i tried to use the compiled one and download the latest from releases, still the same
not working after i run the program and run exitlag 4.95.2 and login with new account still i don't have any trial

**Comment by belalninja** [comment]
also tried to use the script on greasyfork, also doesn't show on violentmonkey script list when I'm on exitlag site nor autofill the email

**Comment by sonatta09** [comment]
mine was working perfectly... use another browser to register new account, mine was chrome on account, then i use microsoft edge, then clear history,data,cookies everytime you register new account... also i never use gmail.. i use developermail.com

**Comment by belalninja** [comment]
basically when you click on confinrm email you will be automatically login, just now i tried Microsoft edge and incognite chrome with deleting all cookies, and tried the program which i always see that it "successfully bypass", also no luck, maybe they now look for IP?

**Comment by sonatta09** [comment]
i just had my trial reset yesterday.. i still have 2days left, let see if i can reset it again

**Comment by bwmsdroid** [comment]
Hey!
I gonna take a look on the issues soon!

**Comment by bwmsdroid** [comment]
![image](https://user-images.githubusercontent.com/53904508/112802442-92362880-9048-11eb-875c-8176b6fa8557.png)
all fine here.
what is your windows version?
what is your exitlag version?

**Comment by bwmsdroid** [comment]
try to logout and login again with the same account, without close exitlag

**Comment by bwmsdroid** [comment]
@sonatta09 "after clicking confirmation do not ever login to your browser". You can login on your browser without any issue.

**Comment by belalninja** [comment]
> ![image](https://user-images.githubusercontent.com/53904508/112802442-92362880-9048-11eb-875c-8176b6fa8557.png)
> all fine here.
> what is your windows version?
> what is your exitlag version?

windows 10 pro 64x 20H2 19042.867
exitlag 4.95.2



> try to login, logout and login again with the same account, without close exitlag

ill try that
thx for reply

**Comment by Angel-C17** [comment]
Hey guys, i tried with different browser and e-mail and it's not working. I have windows 10 Pro 20H2 19042.867, Exitlag 4.95.2. Maybe it's because of the ISP ?

**Comment by bwmsdroid** [comment]
hey!
I made a video explaining!
Check it out!
https://www.youtube.com/watch?v=txR0R4rgy-U
Tell me if you still with problems

**Comment by bwmsdroid** [comment]
They will surely not patch.
Is it working now?

**Comment by belalninja** [comment]
> They will surely not patch.
> Is it working now?

yeah its working now, but i don't know if it works for others
ill close this issue, thx
