### ISSUE TITLE
NO FUNCIONA

### ISSUE THREAD

**Issue by hagensz** [bwmsdroid/exitlag-hwid-bypass#9]
desinstale el programa con revo unistaller, para eliminar todo registro de exitlag, volvi a instalar el programa, elimine los archivos basura de %temp% y de la carpeta %appdata% elimine de local los archivos de la carpeta exitlag lo mismo hice con la carpeta roaming, ejecute la version 1.7 y 1.6 ninguna de las 2 me funciono, me sigue saliendo 0 dias en exitlag, hice varios correos con gmail y correos temporales, nada me funciono hice mas de 60 intentos, aun asi se agradece.

**Comment by bwmsdroid** [comment]
please, english or portuguese;

**Comment by bwmsdroid** [comment]
ow, ok. I got it. 
I am working on a solution, I already know the problem.
This is the same of issue #4, so I am closing this as duplicate.
